name: salary_tracker
description: Track your time.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.2.2<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^1.1.8
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  path_provider: ^2.0.6
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.0
  fluttertoast: ^8.0.8
  wave: ^0.2.0
  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.2
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/salary.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
